[package]
name = "cron"
version = "0.9.0"
authors = ["Zack Slayton <zack.slayton@gmail.com>"]
repository = "https://github.com/zslayton/cron"
documentation = "https://docs.rs/cron"
readme = "README.md"
description = "A cron expression parser and schedule explorer."
keywords = [ "cron", "schedule", "repeat", "periodic", "time" ]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "cron"

[dependencies]
# Disabling default features eliminates a superfluous transitive
# dependency on the `time` crate, which is susceptible to segfaults.
# https://rustsec.org/advisories/RUSTSEC-2020-0071
chrono = { version = "~0.4", default-features = false, features = [] }
nom = "~7"
once_cell = "1.5.2"

[dev-dependencies]
chrono-tz = "0.4"
